  // components/ProfileAndFollowUp.tsx
//
// Two-stage intake flow shown before any decision analysis runs:
//   Stage 1: collect name / age / email (required, validated)
//   Stage 2: adaptive follow-up questions generated by the AI based
//            on the scenario + profile, asked one at a time so each
//            question can depend on the previous answer.
//
// On completion, calls onComplete with the profile + collected Q&A,
// which the parent (app/page.tsx) folds into the final analyze() call.

'use client';
import { useState } from 'react';

export interface CollectedProfile {
  name: string;
  age: number;
  email: string;
}

export interface FollowUpAnswer {
  question: string;
  answer: string;
}

interface ProfileAndFollowUpProps {
  scenario: string;
  onComplete: (profile: CollectedProfile, answers: FollowUpAnswer[], profileId?: string | null) => void;
  onCrisisCheck: (
    text: string,
    source: 'profile_followup',
    context?: { userIdentifier?: string; profileId?: string | null }
  ) => Promise<boolean>;
}

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export default function ProfileAndFollowUp({ scenario, onComplete, onCrisisCheck }: ProfileAndFollowUpProps) {
  const [stage, setStage] = useState<'profile' | 'followup'>('profile');

  // Profile fields
  const [name, setName] = useState('');
  const [age, setAge] = useState('');
  const [email, setEmail] = useState('');
  const [profileErrors, setProfileErrors] = useState<Record<string, string>>({});

  // Follow-up flow
  const [profile, setProfile] = useState<CollectedProfile | null>(null);
  const [savedProfileId, setSavedProfileId] = useState<string | null>(null);
  const [questions, setQuestions] = useState<string[]>([]);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [currentAnswer, setCurrentAnswer] = useState('');
  const [collectedAnswers, setCollectedAnswers] = useState<FollowUpAnswer[]>([]);
  const [loadingQuestions, setLoadingQuestions] = useState(false);
  const [error, setError] = useState('');

  const validateProfile = (): boolean => {
    const errors: Record<string, string> = {};
    if (!name.trim()) errors.name = 'Name is required';
    const ageNum = Number(age);
    if (!age || Number.isNaN(ageNum) || ageNum <= 0 || ageNum > 130) {
      errors.age = 'Enter a valid age';
    }
    if (!email.trim() || !EMAIL_REGEX.test(email.trim())) {
      errors.email = 'Enter a valid email address';
    }
    setProfileErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const submitProfile = async () => {
    if (!validateProfile()) return;

    const collectedProfile: CollectedProfile = { name: name.trim(), age: Number(age), email: email.trim() };
    setProfile(collectedProfile);
    setError('');
    setLoadingQuestions(true);

    try {
      // Fetch the first batch of adaptive follow-up questions, seeded by
      // the scenario + profile. The AI proposes 3 questions up front;
      // we ask them one at a time and could re-fetch deeper questions
      // based on answers, but keep this simple and bounded for now.
      const res = await fetch('/api/profile', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ scenario, profile: collectedProfile }),
      });
      const data = await res.json();
      const qs: string[] = Array.isArray(data.questions) && data.questions.length > 0
        ? data.questions.slice(0, 4)
        : ['What matters most to you in making this decision?'];
      setSavedProfileId(data.profileId ?? null);
      setQuestions(qs);
      setStage('followup');
    } catch {
      setError('Could not generate follow-up questions. You can still continue.');
      setQuestions(['What matters most to you in making this decision?']);
      setStage('followup');
    } finally {
      setLoadingQuestions(false);
    }
  };

  const submitAnswer = async () => {
    if (!currentAnswer.trim()) return;

    // Run the full crisis check on every follow-up answer too —
    // not just the original scenario. Crisis signals can surface
    // anywhere in the conversation.
    if (await onCrisisCheck(currentAnswer, 'profile_followup', {
      userIdentifier: profile?.email,
      profileId: savedProfileId,
    })) {
      return;
    }

    const newAnswers = [...collectedAnswers, { question: questions[currentQuestionIndex], answer: currentAnswer.trim() }];
    setCollectedAnswers(newAnswers);
    setCurrentAnswer('');

    if (currentQuestionIndex + 1 < questions.length) {
      setCurrentQuestionIndex(currentQuestionIndex + 1);
    } else if (profile) {
      onComplete(profile, newAnswers, savedProfileId);
    }
  };

  if (stage === 'profile') {
    return (
      <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm">
        <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-1">Before we begin</p>
        <h2 className="text-lg font-bold text-gray-800 mb-4">A few quick details</h2>

        <div className="space-y-3">
          <div>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Your name"
              className="w-full border border-gray-200 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400"
            />
            {profileErrors.name && <p className="text-xs text-red-500 mt-1">{profileErrors.name}</p>}
          </div>
          <div>
            <input
              type="number"
              value={age}
              onChange={(e) => setAge(e.target.value)}
              placeholder="Your age"
              className="w-full border border-gray-200 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400"
            />
            {profileErrors.age && <p className="text-xs text-red-500 mt-1">{profileErrors.age}</p>}
          </div>
          <div>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="Email address"
              className="w-full border border-gray-200 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400"
            />
            {profileErrors.email && <p className="text-xs text-red-500 mt-1">{profileErrors.email}</p>}
            <p className="text-xs text-gray-400 mt-1">We&apos;ll send your decision plan and flowchart here.</p>
          </div>
        </div>

        {error && <p className="text-xs text-red-500 mt-3">{error}</p>}

        <button
          onClick={submitProfile}
          disabled={loadingQuestions}
          className="mt-4 w-full bg-indigo-600 text-white rounded-xl py-2.5 text-sm font-semibold disabled:opacity-50"
        >
          {loadingQuestions ? 'Preparing questions...' : 'Continue'}
        </button>
      </div>
    );
  }

  // Follow-up question stage
  const progress = ((currentQuestionIndex) / questions.length) * 100;
  return (
    <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm">
      <div className="w-full bg-gray-100 rounded-full h-1.5 mb-4">
        <div className="bg-indigo-500 h-1.5 rounded-full transition-all" style={{ width: `${progress}%` }} />
      </div>
      <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-1">
        Question {currentQuestionIndex + 1} of {questions.length}
      </p>
      <h2 className="text-base font-semibold text-gray-800 mb-4">{questions[currentQuestionIndex]}</h2>

      <textarea
        value={currentAnswer}
        onChange={(e) => setCurrentAnswer(e.target.value)}
        rows={3}
        placeholder="Type your answer..."
        className="w-full border border-gray-200 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400 resize-none"
      />

      <button
        onClick={submitAnswer}
        disabled={!currentAnswer.trim()}
        className="mt-4 w-full bg-indigo-600 text-white rounded-xl py-2.5 text-sm font-semibold disabled:opacity-50"
      >
        {currentQuestionIndex + 1 < questions.length ? 'Next question' : 'See my decision paths →'}
      </button>
    </div>
  );
}
